server {
  listen 4200;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # Rotas do Angular (SPA)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Healthcheck para o Docker
  location /health {
    return 200 'OK';
    add_header Content-Type text/plain;
  }
}

